DROP TABLE IF EXISTS DOMICILIOS;
CREATE TABLE DOMICILIOS (
ID INT AUTO_INCREMENT PRIMARY KEY,
CALLE VARCHAR(100) NOT NULL,
NUMERO INT NOT NULL,
LOCALIDAD VARCHAR(100) NOT NULL,
PROVINCIA VARCHAR(100) NOT NULL);

DROP TABLE IF EXISTS PACIENTES;
CREATE TABLE PACIENTES (
ID INT AUTO_INCREMENT PRIMARY KEY,
APELLIDO VARCHAR(100) NOT NULL,
NOMBRE VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
DNI INT NOT NULL,
FECHA DATE NOT NULL,
DOMICILIO_ID INT NOT NULL);

DROP TABLE IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS (ID INT AUTO_INCREMENT PRIMARY KEY,
NUMEROMATRICULA VARCHAR(100),
NOMBRE VARCHAR(100),
APELLIDO VARCHAR(100));

INSERT INTO DOMICILIOS (CALLE,NUMERO,LOCALIDAD,PROVINCIA)
VALUES ('Calle 1',484,'Salta Capital', 'Salta');

INSERT INTO PACIENTES (APELLIDO, NOMBRE, EMAIL, DNI,FECHA, DOMICILIO_ID) VALUES
('Gambino','Nicolas', 'nicogambino@gmail.com' ,584,'2022-08-25',1);

INSERT INTO ODONTOLOGOS (NUMEROMATRICULA,NOMBRE,APELLIDO) VALUES
('GP1965','Gustavo','Poblete');